export const SET_RESULT_FORM = 'SET_RESULT_FORM'
export const SET_RESULT_FORM_CHECK = 'SET_RESULT_FORM_CHECK'
export const LOAD_IS_EXECUTE = 'LOAD_IS_EXECUTE'
export const SET_PROGRESS_FORM = 'SET_PROGRESS_FORM'
