import { L_CENTER } from '../../../config/config'
import { loadAbiByName, getContract, tx, blockchain, coinbase } from '../../../utils/web3'

function getAbi(lessonName) {
	const abis = {
		Lesson_1: [{'constant':false,'inputs':[{'name':'_air','type':'address'}],'name':'setToken','outputs':[],'type':'function'},{'constant':true,'inputs':[],'name':'reward','outputs':[{'name':'','type':'uint256'}],'type':'function'},{'constant':true,'inputs':[],'name':'air','outputs':[{'name':'','type':'address'}],'type':'function'},{'constant':false,'inputs':[{'name':'_reward','type':'uint256'}],'name':'setReward','outputs':[],'type':'function'},{'constant':false,'inputs':[{'name':'_dao','type':'address'}],'name':'execute','outputs':[],'type':'function'},{'constant':false,'inputs':[{'name':'_owner','type':'address'}],'name':'delegate','outputs':[],'type':'function'},{'constant':true,'inputs':[],'name':'owner','outputs':[{'name':'','type':'address'}],'type':'function'},{'constant':true,'inputs':[{'name':'','type':'address'}],'name':'isPassed','outputs':[{'name':'','type':'bool'}],'type':'function'},{'inputs':[{'name':'_air','type':'address'},{'name':'_reward','type':'uint256'}],'type':'constructor'}],
		Lesson_2: [{'constant':false,'inputs':[{'name':'_air','type':'address'}],'name':'setToken','outputs':[],'type':'function'},{'constant':true,'inputs':[],'name':'reward','outputs':[{'name':'','type':'uint256'}],'type':'function'},{'constant':true,'inputs':[],'name':'air','outputs':[{'name':'','type':'address'}],'type':'function'},{'constant':false,'inputs':[{'name':'_reward','type':'uint256'}],'name':'setReward','outputs':[],'type':'function'},{'constant':false,'inputs':[{'name':'_owner','type':'address'}],'name':'delegate','outputs':[],'type':'function'},{'constant':false,'inputs':[{'name':'_dao','type':'address'},{'name':'_shares_name','type':'string'}],'name':'execute','outputs':[],'type':'function'},{'constant':true,'inputs':[],'name':'owner','outputs':[{'name':'','type':'address'}],'type':'function'},{'constant':true,'inputs':[{'name':'','type':'address'}],'name':'isPassed','outputs':[{'name':'','type':'bool'}],'type':'function'},{'inputs':[{'name':'_air','type':'address'},{'name':'_reward','type':'uint256'}],'type':'constructor'}],
		Lesson_3: [{'constant':false,'inputs':[{'name':'_air','type':'address'}],'name':'setToken','outputs':[],'type':'function'},{'constant':true,'inputs':[],'name':'reward','outputs':[{'name':'','type':'uint256'}],'type':'function'},{'constant':true,'inputs':[],'name':'air','outputs':[{'name':'','type':'address'}],'type':'function'},{'constant':false,'inputs':[{'name':'_reward','type':'uint256'}],'name':'setReward','outputs':[],'type':'function'},{'constant':false,'inputs':[{'name':'_token','type':'address'}],'name':'execute','outputs':[],'type':'function'},{'constant':false,'inputs':[{'name':'_owner','type':'address'}],'name':'delegate','outputs':[],'type':'function'},{'constant':true,'inputs':[],'name':'owner','outputs':[{'name':'','type':'address'}],'type':'function'},{'constant':true,'inputs':[{'name':'','type':'address'}],'name':'isPassed','outputs':[{'name':'','type':'bool'}],'type':'function'},{'inputs':[{'name':'_air','type':'address'},{'name':'_reward','type':'uint256'}],'type':'constructor'}],
		Lesson_4: [{'constant':false,'inputs':[{'name':'_air','type':'address'}],'name':'setToken','outputs':[],'type':'function'},{'constant':true,'inputs':[],'name':'reward','outputs':[{'name':'','type':'uint256'}],'type':'function'},{'constant':true,'inputs':[],'name':'air','outputs':[{'name':'','type':'address'}],'type':'function'},{'constant':false,'inputs':[{'name':'_reward','type':'uint256'}],'name':'setReward','outputs':[],'type':'function'},{'constant':false,'inputs':[{'name':'_shareSale','type':'address'}],'name':'execute','outputs':[],'type':'function'},{'constant':false,'inputs':[{'name':'_owner','type':'address'}],'name':'delegate','outputs':[],'type':'function'},{'constant':true,'inputs':[],'name':'owner','outputs':[{'name':'','type':'address'}],'type':'function'},{'constant':true,'inputs':[{'name':'','type':'address'}],'name':'isPassed','outputs':[{'name':'','type':'bool'}],'type':'function'},{'inputs':[{'name':'_air','type':'address'},{'name':'_reward','type':'uint256'}],'type':'constructor'}],
		Lesson_5: [{'constant':false,'inputs':[{'name':'_air','type':'address'}],'name':'setToken','outputs':[],'type':'function'},{'constant':true,'inputs':[],'name':'reward','outputs':[{'name':'','type':'uint256'}],'type':'function'},{'constant':true,'inputs':[],'name':'air','outputs':[{'name':'','type':'address'}],'type':'function'},{'constant':false,'inputs':[{'name':'_reward','type':'uint256'}],'name':'setReward','outputs':[],'type':'function'},{'constant':false,'inputs':[{'name':'_owner','type':'address'}],'name':'delegate','outputs':[],'type':'function'},{'constant':true,'inputs':[],'name':'owner','outputs':[{'name':'','type':'address'}],'type':'function'},{'constant':true,'inputs':[{'name':'','type':'address'}],'name':'isPassed','outputs':[{'name':'','type':'bool'}],'type':'function'},{'constant':false,'inputs':[{'name':'_token_name','type':'string'},{'name':'_dao','type':'address'}],'name':'execute','outputs':[],'type':'function'},{'inputs':[{'name':'_air','type':'address'},{'name':'_reward','type':'uint256'}],'type':'constructor'}],
		Lesson_6: [{'constant':false,'inputs':[{'name':'_air','type':'address'}],'name':'setToken','outputs':[],'type':'function'},{'constant':true,'inputs':[],'name':'reward','outputs':[{'name':'','type':'uint256'}],'type':'function'},{'constant':true,'inputs':[],'name':'air','outputs':[{'name':'','type':'address'}],'type':'function'},{'constant':false,'inputs':[{'name':'_reward','type':'uint256'}],'name':'setReward','outputs':[],'type':'function'},{'constant':false,'inputs':[{'name':'_market','type':'address'}],'name':'execute','outputs':[],'type':'function'},{'constant':false,'inputs':[{'name':'_owner','type':'address'}],'name':'delegate','outputs':[],'type':'function'},{'constant':true,'inputs':[],'name':'owner','outputs':[{'name':'','type':'address'}],'type':'function'},{'constant':true,'inputs':[{'name':'','type':'address'}],'name':'isPassed','outputs':[{'name':'','type':'bool'}],'type':'function'},{'inputs':[{'name':'_air','type':'address'},{'name':'_reward','type':'uint256'}],'type':'constructor'}],
		Lesson_7: [{'constant':false,'inputs':[{'name':'_air','type':'address'}],'name':'setToken','outputs':[],'type':'function'},{'constant':true,'inputs':[],'name':'reward','outputs':[{'name':'','type':'uint256'}],'type':'function'},{'constant':true,'inputs':[],'name':'air','outputs':[{'name':'','type':'address'}],'type':'function'},{'constant':false,'inputs':[{'name':'_reward','type':'uint256'}],'name':'setReward','outputs':[],'type':'function'},{'constant':false,'inputs':[{'name':'_owner','type':'address'}],'name':'delegate','outputs':[],'type':'function'},{'constant':true,'inputs':[],'name':'owner','outputs':[{'name':'','type':'address'}],'type':'function'},{'constant':true,'inputs':[{'name':'','type':'address'}],'name':'isPassed','outputs':[{'name':'','type':'bool'}],'type':'function'},{'constant':false,'inputs':[{'name':'_market','type':'address'},{'name':'_regulator','type':'address'}],'name':'execute','outputs':[],'type':'function'},{'inputs':[{'name':'_air','type':'address'},{'name':'_reward','type':'uint256'}],'type':'constructor'}],
		Lesson_8: [{'constant':false,'inputs':[{'name':'_air','type':'address'}],'name':'setToken','outputs':[],'type':'function'},{'constant':true,'inputs':[],'name':'reward','outputs':[{'name':'','type':'uint256'}],'type':'function'},{'constant':true,'inputs':[],'name':'air','outputs':[{'name':'','type':'address'}],'type':'function'},{'constant':false,'inputs':[{'name':'_reward','type':'uint256'}],'name':'setReward','outputs':[],'type':'function'},{'constant':false,'inputs':[{'name':'_owner','type':'address'}],'name':'delegate','outputs':[],'type':'function'},{'constant':true,'inputs':[],'name':'owner','outputs':[{'name':'','type':'address'}],'type':'function'},{'constant':true,'inputs':[{'name':'','type':'address'}],'name':'isPassed','outputs':[{'name':'','type':'bool'}],'type':'function'},{'constant':false,'inputs':[{'name':'_market','type':'address'},{'name':'_agent','type':'address'}],'name':'execute','outputs':[],'type':'function'},{'inputs':[{'name':'_air','type':'address'},{'name':'_reward','type':'uint256'}],'type':'constructor'}],
		Lesson_9: [{'constant':false,'inputs':[{'name':'_air','type':'address'}],'name':'setToken','outputs':[],'type':'function'},{'constant':true,'inputs':[],'name':'reward','outputs':[{'name':'','type':'uint256'}],'type':'function'},{'constant':true,'inputs':[],'name':'air','outputs':[{'name':'','type':'address'}],'type':'function'},{'constant':false,'inputs':[{'name':'_reward','type':'uint256'}],'name':'setReward','outputs':[],'type':'function'},{'constant':false,'inputs':[{'name':'_owner','type':'address'}],'name':'delegate','outputs':[],'type':'function'},{'constant':true,'inputs':[],'name':'owner','outputs':[{'name':'','type':'address'}],'type':'function'},{'constant':true,'inputs':[{'name':'','type':'address'}],'name':'isPassed','outputs':[{'name':'','type':'bool'}],'type':'function'},{'constant':false,'inputs':[{'name':'_regulator','type':'address'},{'name':'_asset','type':'address'},{'name':'_rule','type':'address'}],'name':'execute','outputs':[],'type':'function'},{'inputs':[{'name':'_air','type':'address'},{'name':'_reward','type':'uint256'}],'type':'constructor'}],
		Lesson_10: [{'constant':false,'inputs':[{'name':'_air','type':'address'}],'name':'setToken','outputs':[],'type':'function'},{'constant':true,'inputs':[],'name':'reward','outputs':[{'name':'','type':'uint256'}],'type':'function'},{'constant':true,'inputs':[],'name':'air','outputs':[{'name':'','type':'address'}],'type':'function'},{'constant':false,'inputs':[{'name':'_reward','type':'uint256'}],'name':'setReward','outputs':[],'type':'function'},{'constant':false,'inputs':[{'name':'_market','type':'address'}],'name':'execute','outputs':[],'type':'function'},{'constant':false,'inputs':[{'name':'_owner','type':'address'}],'name':'delegate','outputs':[],'type':'function'},{'constant':true,'inputs':[],'name':'owner','outputs':[{'name':'','type':'address'}],'type':'function'},{'constant':true,'inputs':[{'name':'','type':'address'}],'name':'isPassed','outputs':[{'name':'','type':'bool'}],'type':'function'},{'inputs':[{'name':'_air','type':'address'},{'name':'_reward','type':'uint256'}],'type':'constructor'}],
		Lesson_11: [{'constant':false,'inputs':[{'name':'_air','type':'address'}],'name':'setToken','outputs':[],'type':'function'},{'constant':true,'inputs':[],'name':'reward','outputs':[{'name':'','type':'uint256'}],'type':'function'},{'constant':true,'inputs':[],'name':'air','outputs':[{'name':'','type':'address'}],'type':'function'},{'constant':false,'inputs':[{'name':'_reward','type':'uint256'}],'name':'setReward','outputs':[],'type':'function'},{'constant':false,'inputs':[{'name':'_bod','type':'address'}],'name':'execute','outputs':[],'type':'function'},{'constant':false,'inputs':[{'name':'_owner','type':'address'}],'name':'delegate','outputs':[],'type':'function'},{'constant':true,'inputs':[],'name':'owner','outputs':[{'name':'','type':'address'}],'type':'function'},{'constant':true,'inputs':[{'name':'','type':'address'}],'name':'isPassed','outputs':[{'name':'','type':'bool'}],'type':'function'},{'inputs':[{'name':'_air','type':'address'},{'name':'_reward','type':'uint256'}],'type':'constructor'}],
		Lesson_12: [{'constant':false,'inputs':[{'name':'_air','type':'address'}],'name':'setToken','outputs':[],'type':'function'},{'constant':true,'inputs':[],'name':'reward','outputs':[{'name':'','type':'uint256'}],'type':'function'},{'constant':true,'inputs':[],'name':'air','outputs':[{'name':'','type':'address'}],'type':'function'},{'constant':false,'inputs':[{'name':'_reward','type':'uint256'}],'name':'setReward','outputs':[],'type':'function'},{'constant':false,'inputs':[{'name':'_crowdSale','type':'address'}],'name':'execute','outputs':[],'type':'function'},{'constant':false,'inputs':[{'name':'_owner','type':'address'}],'name':'delegate','outputs':[],'type':'function'},{'constant':true,'inputs':[],'name':'owner','outputs':[{'name':'','type':'address'}],'type':'function'},{'constant':true,'inputs':[{'name':'','type':'address'}],'name':'isPassed','outputs':[{'name':'','type':'bool'}],'type':'function'},{'inputs':[{'name':'_air','type':'address'},{'name':'_reward','type':'uint256'}],'type':'constructor'}]
	}
	return abis[lessonName]
}

function execute(lesson, args) {
	return tx(lesson, 'execute', args).
		then((tx)=>{
			return blockchain.subscribeTx(tx)
		})
}

export function run(lessonName, params) {
	var learning_center, lesson
	return loadAbiByName('Core').
		then((abi)=>{
			learning_center = getContract(abi, L_CENTER);
			return getAbi(lessonName)
		}).
		then((abi)=>{
			lesson = getContract(abi, learning_center.getModule(lessonName));
			return execute(lesson, params)
		}).
		then(()=>{
			return lesson.isPassed(coinbase())
		})
}

export function isPassed(number) {
  var learning_center
  var lessonName = 'Lesson_'+ number
  return loadAbiByName('Core').
    then((abi)=>{
      learning_center = getContract(abi, L_CENTER);
      return getAbi(lessonName)
    }).
    then((abi)=>{
      var lesson = getContract(abi, learning_center.getModule(lessonName));
      return lesson.isPassed(coinbase())
    })
}
